console.log("a+b=",a+b)
// console.log("a-b=",a-b)
// console.log("a*b=",a*b)
// console.log("a/b=",a/b)
// console.log("a%b=",a%b)
// console.log("a**b=",a**b)
// console.log("a++=",a++)
// console.log("a--=",a--)
// console.log(a)
// console.log("++a=",++a)
// console.log(a)
// console.log("--a=",--a)
// console.log(a)